### ISSUE TITLE
parse count is off-by-1 in a corner case.

### ISSUE THREAD

**Issue by ampli** [opencog/link-grammar#69]
While running in Windows, I encountered an alloca() out of bound when there is only 1 word in the linkage.
In that case (at least) an assignment is done to pctx->row_starts[1] while only 1 element is allocated.

I did these printouts:

```
char * linkage_print_diagram(const Linkage linkage, bool display_walls, size_t screen_width)
{
    ps_ctxt_t ctx;
    if (!linkage) return NULL;

    ctx.link_heights = (int *) alloca(linkage->num_links * sizeof(int));
    ctx.row_starts = (int *) alloca(linkage->num_words * sizeof(int));
printf("linkage->num_words=%zu\n", linkage->num_words);
    return linkage_print_diagram_ctxt(linkage, display_walls, screen_width, &ctx);
}
```

```
linkage_print_diagram_ctxt(const Linkage linkage, ...
...
        pctx->row_starts[pctx->N_rows] = i - (!print_word_0);    /* PS junk */
    printf("pctx->N_rows=%d\n", pctx->N_rows);
        if (i < N_words_to_print) pctx->N_rows++;     /* same */
```

I got this:

```
$ link-parser he
linkparser> x
Found 1 linkage (1 had no P.P. violations)
    Unique linkage, cost vector = (UNUSED=1 DIS= 0.00 LEN=0)
linkage->num_words=1
pctx->N_rows=1

[x] 
```

Valgrind and ASAN (on Linux) don't catch this problem.
I don't yet understand this code... But maybe allocating one more element will be enough to avoid it.

(BTW, I don't understand why this is a "linkage", and why no null word count is reported.)

**Comment by linas** [comment]
I fixed the mem over-run in commit 405aaf913e89a6c20d2d6ebac4724b67b0178dab

**Comment by linas** [comment]
I think the mem over-run was exposed by the hebrew dict, since it does not use a left/right wall

**Comment by ampli** [comment]
Indeed. But it still doesn't explain why this is considered by the code to be a valid linkage.

**Comment by linas** [comment]
Well, the miscount is happening at line 210 of count.c but I don't see a fix.    The test there is that: if two words are next to each other, and there are no dangling connectors, then everything must be good and so it counts 1.  But in this case, there are no connectors at all ... which is an equivalent condition.

**Comment by linas** [comment]
also: the bug will go away if you add left, right walls to he, because that way, there will always be at least one link, from left to the right wall....

**Comment by ampli** [comment]
> $ link-parser he
> linkparser> x
> Found 1 linkage (1 had no P.P. violations)
>     Unique linkage, cost vector = (UNUSED=1 DIS= 0.00 LEN=0)
>
> [x] 

This problem (of indicating a complete linkage when there is none) doesn't exists by now.
But another one exists instead (a duplicate linkage):
``` text
linkparser> x
No complete linkages found.
Found 2 linkages (2 had no P.P. violations) at null count 1
	Linkage 1, cost vector = (UNUSED=2 DIS= 0.00 LEN=0)

LEFT-WALL [x]

Press RETURN for the next linkage.
linkparser> 
	Linkage 2, cost vector = (UNUSED=2 DIS= 0.00 LEN=0)

LEFT-WALL [x]
```

This problem (of duplicate linkages resulting from "empty disjuncts") has been solved in PR #1042 (waiting for application).
